routes/authentication.py
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from forms.login import LoginForm
from models.users import Users
from models.utils import verify_pass

blueprint = Blueprint('authentication', __name__, url_prefix='')


@blueprint.route('/login', methods=["GET", "POST"])
def login():
    login_form = LoginForm(request.form)

    if 'login' in request.form:

        username = request.form['username']
        password = request.form['password']

        user = Users.query.filter_by(username=username).first()

        if user and verify_pass(password, user.password):
            login_user(user)
            return redirect(url_for('home.dashboard'))

        return render_template('accounts/login.html',
                               msg='Usuario o contraseña incorrecto',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    else:
        return redirect(url_for('home.dashboard'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

templates/includes/footer.html
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    &copy; <a target="_blank" rel="noopener noreferrer" href="#">2024</a>
    NOMBRE EMPRESA <a target="_blank" rel="noopener noreferrer" href="#"></a>
    <div class="float-right d-none d-sm-inline-block">
      <a target="_blank" rel="noopener noreferrer" 
          href="#">v1.0.1</a>
    </div>
  </footer>

templates/includes/navigation.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

templates/includes/scripts.html
<!-- jQuery -->
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/static/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/static/assets/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/static/assets/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/static/assets/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/static/assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/static/assets/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/static/assets/plugins/moment/moment.min.js"></script>
<script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/static/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/static/assets/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/static/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/assets/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/static/assets/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/assets/js/demo.js"></script>

templates/includes/sidebar.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/static/assets/img/logos/logo_sm_white.png" alt="AdminLTE Logo" class="brand-image " style="opacity: .8;">
      <span class="brand-text font-weight-light">NOMBRE EMPRESA</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">

        <div class="info text-white">
            Usuario: {{ current_user.username }}
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            {% if current_user.role == 0 %}
            <a href="/users" class="nav-link {% if 'users' in segment %} active {% endif %}">
              <i class="nav-icon fas fa-user"></i>
              <p> Usuarios</p>
            </a>
            <a href="/system_config/form" class="nav-link {% if 'system_config' in segment %} active {% endif %}">
              <i class="nav-icon fas fa-cog"></i>
              <p> Config. Sistema</p>
            </a>
            {% endif %}
            <a href="{{ url_for('authentication.logout') }}" class="nav-link">
              <i class="nav-icon fas fa-arrow-alt-circle-left"></i>
              <p> Cerrar Sesión</p>
            </a>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->

  </aside>
    <div class="modal fade" id="bank_modal" tabindex="-1" role="dialog" aria-labelledby="bank_modal"
         aria-hidden="true">
    </div>
  <script>

      var status = "{{ current_user.status }}"
      if (status != "1")
        window.location.href = "/page-401"

  </script>